### ISSUE TITLE
Meta-issue: dumb imitation baselines

### ISSUE THREAD

**Issue by qxcv** [HumanCompatibleAI/imitation#16]
In addition to our fancy adversarial & maxent algorithms, we should also consider having some simple baselines for imitation. In descending order of importance, these could/should include:

- [x] Behavioural cloning (in progress by @qxcv)
- [ ] Soft RL with soft behavioural cloning. Fit a rough density estimate `\hat\pi_E(a|s)` to the expert demonstrations with BC, then use `\log \hat \pi_E(a|s) \approx A^\star(s,a)` as a reward function to train an imitation agent.
- [ ] Try state-based density estimates instead of action-based density estimates. Specifically, you could put a Gaussian around each of the demonstration trajectories and reward the agent with the log likelihood of the states it visits under those Gaussians. If we only have one trajectory `\tau = (s_1, s_2, \ldots, s_T)` (ignoring actions), then the reward function would be `r_t(\hat s_t, \hat a_t) = \|\hat s_t - s_t\|^2`, where `s_t` is the demo state at time `t` from trajectory `\tau`. This is a silly version of what [DeepMimic](https://xbpeng.github.io/projects/DeepMimic/2018_TOG_DeepMimic.pdf) does. I don't expect this to work very well, but it would be good at keeping us honest on how well the parametric methods are doing.

**Comment by AdamGleave** [comment]
Big :+1: to this, especially behavioral cloning.

**Comment by qxcv** [comment]
Will start working on BC today.
